### PR TITLE
add-teammember-theme-support

### PR DESCRIPTION
**Pull request by boskya**
Addresses issue #70 

### Review
 - [x] @jtrinklein
 - [ ] @joebri

### After Merge

run:

```
git checkout master
git pull
npm version patch
```

### note

If npm version is `2.13` or later npm version will likely fail to run postversion script, leaving you with pending commits in your repo.

If this is the case, run `npm run-script postversion` to finish the process.

### CODE REVIEW

**Comment by jtrinklein** [comment]
where are the italic fonts getting used?

**Comment by boskya** [comment]
No where..suppose I should remove them? I just have them there because I copied the entire fonts folder.

**Comment by jtrinklein** [comment]
i'm not sure, is there a way we can define that those fonts are used when we use the museo family with the italic font-style?

**Comment by boskya** [comment]
we can add new font-face - where we define font-weight as part of font face. I can go ahead and do that..so that people don't inadvertently use the italic font

**Comment by boskya** [comment]
ok that won't work

**Comment by jtrinklein** [comment]
ok well it was just a curiosity anyway, i'm good with the changes. even though you didn't add any screen shots :smiley: 
:tophat:
:godmode:
:shirt::+1:
:jeans:

**Comment by boskya** [comment]
I am disappointed with myself 
screen shot 2016-01-18 at 1 38 40 pm

**Comment by jtrinklein** [comment]
much better :tada:

**Pull request merged**
